navikt/fritakagp

- deploy/dev.yaml
- src/main/kotlin/no/nav/helse/fritakagp/integration/altinn/CachedAuthRepo.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/PreprodKoinProfile.kt
- src/main/resources/application.conf
Har konfigurert opp tilganger i api-management (slack: #apigw)
Hentet tilgangsnøkler i vault og lagt disse i en k8 secret i gcp.
Konfigurert opp en altinnklient i preprod-profilen
> Legger til cachet integrasjon mot rettigheter i Altinn

- build.gradle.kts
- src/main/kotlin/no/nav/helse/fritakagp/App.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/GravidRoutes.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/KroniskRoutes.kt
- src/main/resources/logback.xml
- src/test/kotlin/no/nav/helse/fritakagp/processing/ProcessingTestUtils.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravProcessorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadProcessorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravProcessorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadProcessorTest.kt
Oppretter fordelingsoppgave når prosesseringen av skjema gis opp.
> Poh 179 fordelignsoppgaver

- src/main/kotlin/no/nav/helse/fritakagp/web/api/GravidRoutes.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/KroniskRoutes.kt
- src/test/kotlin/no/nav/helse/slowtests/systemtests/api/GravidKravHTTPTests.kt
- src/test/kotlin/no/nav/helse/slowtests/systemtests/api/GravidSoeknadHTTPTests.kt
- src/test/kotlin/no/nav/helse/slowtests/systemtests/api/KroniskKravHTTPTests.kt
- src/test/kotlin/no/nav/helse/slowtests/systemtests/api/KroniskSoeknadHTTPTests.kt
POH 668 hente ut skjema, kun mulig for den som det er søkt/krevet på vegne av
> Endepunkter og tester for å hente skjemaer via GET

- src/main/resources/validation/validation-messages.properties
Endrer feilmelding ved manglende arbeidsforhold i `.../fritak-agp/nb/gravid/krav` ref. [POH-983](https://jira.adeo.no/browse/POH-983)
> POH-983 Endrer feilmelding for manglende arbeidsforhold

- src/main/kotlin/no/nav/helse/fritakagp/domain/GravidKrav.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/GravidSoeknad.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/KroniskKrav.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/KroniskSoeknad.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/LocalKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/PreprodKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ProdKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/service/PdlService.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/FritakModule.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/GravidRoutes.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/KroniskRoutes.kt
- src/test/kotlin/no/nav/helse/GravidTestData.kt
- src/test/kotlin/no/nav/helse/KroniskTestData.kt
[Ticket](https://jira.adeo.no/browse/POH-1026)
Adds name instead of fnr in sendtAv to routes:
```
/api/v1/gravid/soeknad/<uuid>
/api/v1/gravid/krav/<uuid>
/api/v1/kronisk/soeknad/<uuid>
/api/v1/kronisk/krav/<uuid>
```
> Adds name to 'sendtAv' instead of fnr

- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravKvittering.kt
Legger til sykmeldingsgrad i altinn-kvittering for refusjon krav og gravid
> Legger til sykmeldingsgrad i altinn-kvittering for refusjon

- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/GravidResReq.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/KroniskResReq.kt
- src/test/kotlin/no/nav/helse/fritakagp/web/api/resreq/GravidKravRequestTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/web/api/resreq/KroniskKravRequestTest.kt
Det skal ikke være mulig å sende inn tomt antall dager til krav. Antall dager må være 1-366.
> Validering: Antall dager høyere enn 0

- src/main/kotlin/no/nav/helse/fritakagp/web/api/GravidRoutes.kt
- src/test/kotlin/no/nav/helse/slowtests/systemtests/api/OppdaterGravidKravHTTPTests.kt
- src/test/kotlin/no/nav/helse/slowtests/systemtests/api/SlettGravidKravHTTPTests.kt
- Legger til `patch("/{id}")` for gravidKrav
Todo:
- Sjekke om krav allerede er slettet/endret
- Kun tillate at enkelte felt endres
- Sette status på nyopprettet krav (?)
- Flere tester
> Legger til endre krav rute

- src/main/kotlin/no/nav/helse/fritakagp/web/api/GravidRoutes.kt
Koden som bruker denne funksjonen ble fjernet 24/6/2021, se:
https://github.com/navikt/fritakagp/commit/c5d9a75aa795209616af4a04f3a95c367492a15d
> Det ser ut som koden som brukte funksjonen ble fjernet 24/6/2021

- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravPDFGenerator.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravPDFGenerator.kt
- src/test/kotlin/no/nav/helse/GravidTestData.kt
- src/test/kotlin/no/nav/helse/KroniskTestData.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravPDFGeneratorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravPDFGeneratorTest.kt
https://trello.com/c/yjd3iU6o/62-fritakagp-krav-journaldokument
> Legger til flere sider i pdf for hver fjerde krav-periode

- .github/workflows/main.yml
- .github/workflows/test.yml
- build.gradle.kts
> Sonar analyse aktiv

- src/main/kotlin/no/nav/helse/fritakagp/domain/KroniskSoeknad.kt
- src/test/kotlin/no/nav/helse/KroniskTestData.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadAntallDagerFloatTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/web/api/resreq/KroniskSoknadRequestTest.kt
- src/test/kotlin/no/nav/helse/slowtests/systemtests/api/KroniskSoeknadHTTPTests.kt
Må kunne sende inn halve dager for de som er delvis sykemeldte.
> Aksepter halve dager som parameter

- Dockerfile
- src/main/kotlin/no/nav/helse/fritakagp/service/MDCOperations.kt
`SecureRandom` er overkill her.
> Fjern SecureRandom

- src/main/kotlin/no/nav/helse/fritakagp/koin/LocalKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/PreprodKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ProdKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravSlettProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravSlettProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/GravidRoutes.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/KroniskRoutes.kt
Må oppdatere helsearbeidsgiver-arbeidsgiver-notifikasjon-klient først som avhenger av ktor versjon bla.
> Legger til softdelete i rute, harddelete i bakgrunnsjobb

- src/main/kotlin/no/nav/helse/fritakagp/koin/LocalKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/PreprodKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ProdKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravSlettProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravSlettProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/GravidRoutes.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/KroniskRoutes.kt
> Revert "Legger til softdelete i rute, harddelete i bakgrunnsjobb"

- src/main/kotlin/no/nav/helse/fritakagp/processing/arbeidsgivernotifikasjon/ArbeidsgiverNotifikasjonProcessor.kt
ref. https://trello.com/c/UGQCWYGj/175-fritakagp-sak
> Endring av tekst i overskrift på sak til arbeidsgiver.

- src/main/kotlin/no/nav/helse/fritakagp/domain/GravidKrav.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/GravidSoeknad.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/KroniskKrav.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/KroniskSoeknad.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/utils.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravKvittering.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravPDFGenerator.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravSlettProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadKvittering.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadPDFGenerator.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravKvittering.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravPDFGenerator.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravSlettProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadKafkaProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadKvittering.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadKvitteringProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadPDFGenerator.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/soeknad/KroniskSoeknadProcessor.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravPDFGeneratorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/soeknad/GravidSoeknadPDFGeneratorTest.kt
> Diverse ønsker fra NAY

- http/arbeidsgiver.http
Bruker https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
> Legg til http-fil for å kjøre mot lokal app

- src/main/kotlin/no/nav/helse/fritakagp/JsonUtils.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/GravidKrav.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/KravForOppgave.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/KroniskKrav.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/KoinProfiles.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/KoinUtils.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/PreprodKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravProcessor.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravProcessor.kt
- src/test/kotlin/no/nav/helse/fritakagp/TestUtils.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravProcessorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravProcessorTest.kt
- src/test/resources/gravidKravRobotBeskrivelse.json
- src/test/resources/kroniskKravRobotBeskrivelse.json
Oversikt over hvilke endringer som trengs hvis oppgaver skal robotiseres
> Robotisering av oppgaver i fritak

- deploy/dev.yml
- deploy/prod.yml
- src/main/kotlin/no/nav/helse/fritakagp/App.kt
- src/main/kotlin/no/nav/helse/fritakagp/Env.kt
- src/main/resources/application.conf
Fjerner en eldgammel toggle som alltid er true.
> Fjern toggle for bakgrunnsjobber

- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravProcessor.kt
Bugfix etter major upgrade i forrige uke.
(var: "Søknad om refusjon...", rettet til "Krav om refusjon...")
> journalfør kronisk krav med korrekt journalføringstittel

- src/main/kotlin/no/nav/helse/arbeidsgiver/bakgrunnsjobb2/BakgrunnsjobbRepository.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/bakgrunnsjobb2/BakgrunnsjobbService.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/bakgrunnsjobb2/ParallellBakgrunnsjobbService.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/bakgrunnsjobb2/utils/RecurringJob.kt
- src/main/kotlin/no/nav/helse/fritakagp/App.kt
- src/main/kotlin/no/nav/helse/fritakagp/datapakke/DatapakkePublisherJob.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/LocalKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/PreprodKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ProdKoinProfile.kt
- src/test/kotlin/no/nav/helse/slowtests/ParallellBakgrunnsjobbServiceTest.kt
Oppslag mot vår database tar lang tid, så må speede opp litt ved å kjøre flere requests i parallell
> parallellkjøring av oppdaterArbeidsgivernotifikasjon

- .github/workflows/ktlint.yml
- .github/workflows/main.yml
- .github/workflows/prod.yml
- .github/workflows/test.yml
`gradle/gradle-build-action@v3` erstattes med `gradle/actions/setup-gradle@v3`. Se https://github.com/gradle/gradle-build-action/releases/tag/v3.0.0.
> Bump workflows-avhengigheter

- deploy/nais.yml
- docker/local/postgres/postgres.Dockerfile
Merger og prodsetter denne rett etter migrering av databasen i prod
> oppgradert til postgres 14

- src/main/kotlin/no/nav/helse/fritakagp/domain/KroniskSoeknad.kt
"Søknad om refusjon av" -> "Søknad om fritak fra"
> tekstendring på tittel kroniskSoeknad

- deploy/dev.yml
- deploy/prod.yml
- src/main/kotlin/no/nav/helse/fritakagp/integration/norg/Norg2Client.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/Fakes.kt
> bytt til norg-proxy for å finne behandlende enehet.

- deploy/dev.yml
- deploy/nais.yml
- deploy/prod.yml
Endret config til å ta array av scopes
> Endret config til å ta array av scopes

- build.gradle.kts
Testet OK i dev
Noen nye warnings pga deprecated stuff ved kompilering - kan se på disse senere.
> bumpet kotlin og kotlinx-serialization

- build.gradle.kts
- gradle.properties
- src/main/kotlin/no/nav/helse/fritakagp/koin/Fakes.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/KoinProfiles.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/ApiExceptionHandling.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/GravidResReq.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/KroniskResReq.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/validation/CustomValidatorConstraints.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/validation/ProblemFramework.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/validation/Validators.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravProcessorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravProcessorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/web/api/resreq/validation/AaregConstraintsKtTest.kt
> faser ut felles-backend

- build.gradle.kts
- src/main/kotlin/no/nav/helse/fritakagp/auth/AuthClient.kt
Lagt inn logging av expiresInSeconds for å vurdere evt. cashing av maskinportentoken.
Oppgraderer til Apache5 for httpClient
> logging av expiresInSeconds og Apache5 oppgradering

- build.gradle.kts
- gradle.properties
- src/main/kotlin/no/nav/helse/fritakagp/Env.kt
- src/main/kotlin/no/nav/helse/fritakagp/auth/AuthClient.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
- src/main/resources/application.conf
Fjerner gmale maskinportenklient siden vi bruker Texas for å hente token.
> Fjernemaskinporten

- .github/workflows/main.yml
- deploy/dev.yml
- deploy/nais.yml
- deploy/prod.yml
- src/main/kotlin/no/nav/helse/fritakagp/App.kt
- src/main/kotlin/no/nav/helse/fritakagp/Env.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/FritakModule.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/auth/LocalAuthTokenDispenser.kt
- src/main/resources/application.conf
Mange tjenester i Nav krever TokenX, deriblant Fager sitt API for å hente Altinn-tilganger, som vi skal koble oss på i neste omgang.
> Legg til støtte for TokenX

- deploy/dev.yml
- deploy/nais.yml
- deploy/prod.yml
- src/main/kotlin/no/nav/helse/fritakagp/Env.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/PreprodKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/koin/ProdKoinProfile.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/FritakModule.kt
- src/main/resources/application.conf
Fjerner idporten config siden vi har gått over til tokenx
fjerner også diverse config vi ikke bruke lenger.
> Fjern Idporten og diverse config

- .github/workflows/main.yml
- .github/workflows/prod.yml
- deploy/nais.yml
Endret workflow til å bruke Google Artifact Registry. 
Testet i dev men ikke i produksjon.
> Migrere til GAR

- deploy/dev.yml
Bytter aura til nais namespace for tokenx generator
Se [tråd](https://nav-it.slack.com/archives/C60FFACN5/p1740985537800509) for context
> Bytt aura til nais namespace

- src/main/kotlin/no/nav/helse/fritakagp/web/api/KroniskRoutes.kt
Logg callID til aareg ifbm debugging av kronisk krav
> logg callId i aareg-oppslag

- docker/local/docker-compose.yml
- src/main/kotlin/no/nav/helse/fritakagp/web/api/KroniskRoutes.kt
Bitnami-image er utdatert og er ikke tilgjengelig fra og med i dag; 
https://hub.docker.com/r/bitnami/kafka
> Oppgrader kafka i dockerfile

- gradle.properties
Ny versjon av aareg-klienten har 10 sekunder timeout-grense på kallene til aareg
> bumper aaregClient (øker http timeout-grensene)

- src/main/kotlin/no/nav/helse/fritakagp/domain/AarsakEndring.kt
- src/main/kotlin/no/nav/helse/fritakagp/domain/utils.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravPDFGenerator.kt
- src/main/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravPDFGenerator.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/RequestHandler.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/GravidResReq.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/KroniskResReq.kt
- src/main/kotlin/no/nav/helse/fritakagp/web/api/route/GravidRoutes.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/gravid/krav/GravidKravPDFGeneratorTest.kt
- src/test/kotlin/no/nav/helse/fritakagp/processing/kronisk/krav/KroniskKravPDFGeneratorTest.kt
Legger til endringsårsak i backendmodellen.
Legger til endringsårsaken i journalført dokument og gosys oppgave beskrivelse
> Legg til endringsårsak
